version: '2'

services:
 
  metabase:   
    build:
      context: metabase
      dockerfile: metabase.Dockerfile
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - "MB_DB_FILE=/metabase-data/metabase.db" 
    ports: 
      - "3000:3000"